spring.application.name=Remote-Education-Host
spring.datasource.url=jdbc:postgresql://localhost:5432/remote education host
spring.datasource.username=postgres
spring.datasource.password=13052004

spring.datasource.driver-class-name=org.postgresql.Driver
