spring.application.name=Remote-Education-Host
spring.datasource.url=jdbc:postgresql://localhost:5432/remote education host
spring.datasource.username=postgres
spring.datasource.password=13052004

spring.datasource.driver-class-name=org.postgresql.Driver

logging.level.org.springframework.security=DEBUG

#spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:authz.pub
#spring.security.oauth2.resourceserver.jwt.audiences=REH-client
#spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:9000
#spring.security.oauth2.resourceserver.jwt.issuer-uri: https://idp.example.com/issuer